# Generated by Django 3.2.9 on 2021-12-14 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_restaurantlist_menu_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItems',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='restmenuitems',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='RestMenuItems',
        ),
    ]
